### ISSUE TITLE
Build fails with `Error: Type 'FontFeature' not found.`

### ISSUE THREAD

**Issue by ethan-chaplin** [AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language#560]
Building FML currently fails, as the `google_fonts` package has been updated with breaking changes to version 6.2.0. The current fix is to lock google_fonts at version 6.1.0.

Stack Trace:
```
Target dart2js failed: ProcessException: Process exited abnormally:
../../../AppData/Local/Pub/Cache/hosted/pub.dev/google_fonts-6.2.0/lib/src/google_fonts_base.dart:69:8:
Error: Type 'FontFeature' not found.
  List<FontFeature>? fontFeatures,
       ^^^^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/google_fonts-6.2.0/lib/src/google_fonts_base.dart:69:8:
Error: 'FontFeature' isn't a type.
  List<FontFeature>? fontFeatures,
       ^^^^^^^^^^^
lib/widgets/camera/stream/stream.dart:8:32:
Warning: Operand of null-aware operation '!' has type 'View' which excludes null.
 - 'View' is from 'package:fml/widgets/camera/stream/stream.web.dart' ('lib/widgets/camera/stream/stream.web.dart').
  factory StreamView(model) => getView(model)!;
                               ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/cross_file-0.3.3+8/lib/src/types/html.dart:136:42:
Warning: Operand of null-aware operation '!' has type 'int' which excludes null.
    if (isSafari() && _length != null && _length! >= _fourGigabytes) {
                                         ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_code_editor-0.3.1/lib/src/gutter/gutter.dart:93:28:
Warning: Operand of null-aware operation '!' has type 'List<Widget>' which excludes null.
 - 'List' is from 'dart:core'.
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('../flutter/packages/flutter/lib/src/widgets/framework.dart').
      tableRows[lineIndex].children![_lineNumberColumn] = Text(
                           ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_code_editor-0.3.1/lib/src/gutter/gutter.dart:111:28:
Warning: Operand of null-aware operation '!' has type 'List<Widget>' which excludes null.
 - 'List' is from 'dart:core'.
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('../flutter/packages/flutter/lib/src/widgets/framework.dart').
      tableRows[lineIndex].children![_issueColumn] = GutterErrorWidget(
                           ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_code_editor-0.3.1/lib/src/gutter/gutter.dart:130:28:
Warning: Operand of null-aware operation '!' has type 'List<Widget>' which excludes null.
 - 'List' is from 'dart:core'.
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('../flutter/packages/flutter/lib/src/widgets/framework.dart').
      tableRows[lineIndex].children![_foldingColumn] = FoldToggle(
                           ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_code_editor-0.3.1/lib/src/gutter/gutter.dart:147:28:
Warning: Operand of null-aware operation '!' has type 'List<Widget>' which excludes null.
 - 'List' is from 'dart:core'.
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('../flutter/packages/flutter/lib/src/widgets/framework.dart').
      tableRows[lineIndex].children![_foldingColumn] = FoldToggle(
                           ^
Error: Compilation failed.
  Command: C:\Users\ac87161\Random_Projects\MASDA\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
  C:\Users\ac87161\Random_Projects\MASDA\flutter\bin\cache\dart-sdk\bin\snapshots\dart2js.dart.snapshot
  --platform-binaries=C:\Users\ac87161\Random_Projects\MASDA\flutter\bin\cache\flutter_web_sdk\kernel --invoker=flutter_tool
  -Ddart.vm.product=true -DFLUTTER_WEB_AUTO_DETECT=true
  -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/f40e976bedff57e69e1b3d89a7c2a3c617a03dad/
  --native-null-assertions --no-source-maps -o
  C:\Users\ac87161\Random_Projects\MASDA\Flutter-Markup-Language\.dart_tool\flutter_build\b779e5d85af94553c9f66d8f8452d663\app.dill      
  --packages=.dart_tool/package_config.json --cfe-only
  C:\Users\ac87161\Random_Projects\MASDA\Flutter-Markup-Language\.dart_tool\flutter_build\b779e5d85af94553c9f66d8f8452d663\main.dart     
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:127:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:280:19)
<asynchronous suspension>
#2      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:189:5)
<asynchronous suspension>
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:853:9)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:620:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:89:34)
<asynchronous suspension>
#10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:199:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1367:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

**Comment by Omo-oba18** [comment]
hello, i downgraded the google_fonts but the issue is still there! I was using version 6.1.0 i downgraded to 6.0.0 but still the same error

**Comment by ethan-chaplin** [comment]
Ensure that your pubspec.yaml isn't using a version like `^6.1.0`, and hardcode it to 6.1.0. #561 is my fix and it works on my system
